In [15]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# ======================================
# Manual KNN Functions
# ======================================

def euclidean_distance(a,b):
    return np.sqrt(np.sum((a-b)**2))

def knn_predict(X_train,y_train,X_test,k):

    predictions = []

    for test in X_test:

        distances = []

        for i in range(len(X_train)):
            dist = euclidean_distance(test,X_train[i])
            distances.append((dist,y_train[i]))

        distances.sort(key=lambda x:x[0])

        neighbors = distances[:k]

        labels = [n[1] for n in neighbors]

        prediction = max(set(labels), key=labels.count)

        predictions.append(prediction)

    return predictions


# ==================================================
# 1. IRIS DATASET - USING SKLEARN
# ==================================================

print("\n----- IRIS (KNN USING LIBRARY) -----")

iris = pd.read_csv("iris.csv")

X = iris.drop("species",axis=1)
y = iris["species"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))


# ==================================================
# 2. IRIS DATASET - WITHOUT LIBRARY
# ==================================================

print("\n----- IRIS (MANUAL KNN) -----")

X = iris.drop("species",axis=1).values
y = iris["species"].values

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

predictions = knn_predict(X_train,y_train,X_test,3)

print("Accuracy:",accuracy_score(y_test,predictions))
print("Confusion Matrix:\n",confusion_matrix(y_test,predictions))
print("Classification Report:\n",classification_report(y_test,predictions))


# ==================================================
# 3. DIABETES DATASET - USING SKLEARN (WITH SCALING)
# ==================================================

print("\n----- DIABETES (KNN USING LIBRARY) -----")

diabetes = pd.read_csv("diabetes.csv")

X = diabetes.drop("Outcome",axis=1)
y = diabetes["Outcome"]

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))


# ==================================================
# 4. DIABETES DATASET - WITHOUT LIBRARY
# ==================================================

print("\n----- DIABETES (MANUAL KNN) -----")

diabetes = pd.read_csv("diabetes.csv")

X = diabetes.drop("Outcome",axis=1).values
y = diabetes["Outcome"].values

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

predictions = knn_predict(X_train,y_train,X_test,5)

print("Accuracy:",accuracy_score(y_test,predictions))
print("Confusion Matrix:\n",confusion_matrix(y_test,predictions))
print("Classification Report:\n",classification_report(y_test,predictions))


# ==================================================
# 5. HEART DATASET - USING LIBRARY (BEST K SEARCH)
# ==================================================

print("\n----- HEART DATASET -----")

heart = pd.read_csv("heart.csv")

X = heart.drop("target",axis=1)
y = heart["target"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

best_k = 1
best_score = 0

for k in range(1,15):

    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train,y_train)

    pred = knn.predict(X_test)
    score = accuracy_score(y_test,pred)

    if score > best_score:
        best_score = score
        best_k = k

print("Best K:",best_k)

knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

print("Accuracy:",accuracy_score(y_test,y_pred))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))


----- IRIS (KNN USING LIBRARY) -----
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


----- IRIS (MANUAL KNN) -----
Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00   